"use client";
import React from "react";
import * as _Builtin from "./_Builtin";
import * as _utils from "./utils";
import _styles from "./About4.module.css";

export function About4({ as: _Component = _Builtin.Block }) {
  return (
    <_Component
      className={_utils.cx(
        _styles,
        "section_home_how-it-works",
        "about_location"
      )}
      tag="section"
    >
      <_Builtin.Block
        className={_utils.cx(_styles, "section_home_how-it-works")}
        tag="section"
      >
        <_Builtin.Block
          className={_utils.cx(_styles, "padding-global")}
          tag="div"
        >
          <_Builtin.Block
            className={_utils.cx(_styles, "container-large")}
            tag="div"
          >
            <_Builtin.Block
              className={_utils.cx(_styles, "padding-section-large")}
              tag="div"
            >
              <_Builtin.Block
                className={_utils.cx(_styles, "home_how-it-works_component")}
                tag="div"
              >
                <_Builtin.Block
                  className={_utils.cx(
                    _styles,
                    "margin-bottom",
                    "margin-xxlarge",
                    "mob"
                  )}
                  tag="div"
                >
                  <_Builtin.Block
                    className={_utils.cx(
                      _styles,
                      "div-block-3",
                      "landscape",
                      "mob"
                    )}
                    tag="div"
                  >
                    <_Builtin.Heading
                      className={_utils.cx(_styles, "heading-7", "mob")}
                      tag="h1"
                    >
                      <_Builtin.Strong>
                        <_Builtin.Emphasized
                          className={_utils.cx(
                            _styles,
                            "italic-text-2",
                            "service_head",
                            "lanndscape",
                            "mob"
                          )}
                        >
                          {"LOCATIONS"}
                        </_Builtin.Emphasized>
                      </_Builtin.Strong>
                      {""}
                    </_Builtin.Heading>
                    <_Builtin.Block
                      className={_utils.cx(_styles, "div-block-4", "mob")}
                      tag="div"
                    >
                      <_Builtin.Image
                        className={_utils.cx(_styles, "landscape", "mob")}
                        loading="lazy"
                        height="auto"
                        width="103"
                        alt=""
                        src="https://uploads-ssl.webflow.com/6547e1150d1404495b9400cd/655ac7e055c5599d1d61725b_Line%2021.svg"
                      />
                      <_Builtin.Paragraph
                        className={_utils.cx(_styles, "paragraph-3")}
                      >
                        <_Builtin.Strong>
                          <_Builtin.Emphasized
                            className={_utils.cx(
                              _styles,
                              "italic-text-3",
                              "landscape",
                              "mobtext"
                            )}
                          >
                            {"LOCATIONS"}
                          </_Builtin.Emphasized>
                        </_Builtin.Strong>
                      </_Builtin.Paragraph>
                    </_Builtin.Block>
                  </_Builtin.Block>
                </_Builtin.Block>
                <_Builtin.Block
                  className={_utils.cx(
                    _styles,
                    "div-block-5",
                    "tabsize",
                    "mob"
                  )}
                  tag="div"
                >
                  <_Builtin.Heading
                    className={_utils.cx(
                      _styles,
                      "heading-9",
                      "landhead",
                      "mob"
                    )}
                    tag="h1"
                  >
                    <_Builtin.Emphasized
                      className={_utils.cx(
                        _styles,
                        "heading-white",
                        "landhead",
                        "mob"
                      )}
                    >
                      {"WE HAVE A CAR WORKSHOP NEAR YOU"}
                    </_Builtin.Emphasized>
                    {""}
                  </_Builtin.Heading>
                  <_Builtin.Paragraph
                    className={_utils.cx(_styles, "paragraph-4", "paraland")}
                  >
                    {
                      "At vitae commodo amet libero tortor blandit risus condimentum mauris. Cras arcu tortor aenean turpis massa mauris ac mi facilisi cursus."
                    }
                  </_Builtin.Paragraph>
                </_Builtin.Block>
                <_Builtin.Grid
                  className={_utils.cx(_styles, "home_how-it-works_list")}
                  tag="div"
                >
                  <_Builtin.Block
                    className={_utils.cx(
                      _styles,
                      "home_how-it-works_item",
                      "landscape"
                    )}
                    id={_utils.cx(
                      _styles,
                      "w-node-_08271253-e666-3828-5306-700e78623ee1-78623ec6"
                    )}
                    tag="div"
                  >
                    <_Builtin.Block
                      className={_utils.cx(
                        _styles,
                        "margin-bottom",
                        "margin-medium"
                      )}
                      tag="div"
                    >
                      <_Builtin.Block
                        className={_utils.cx(
                          _styles,
                          "home4-features_image-wrapper"
                        )}
                        tag="div"
                      >
                        <_Builtin.Image
                          className={_utils.cx(
                            _styles,
                            "home_how-it-works_image"
                          )}
                          loading="lazy"
                          height="auto"
                          width="400"
                          alt=""
                          src="https://uploads-ssl.webflow.com/6547e1150d1404495b9400cd/654c759f824c04859c7cdf05_Group%2026.png"
                        />
                        <_Builtin.Block
                          className={_utils.cx(
                            _styles,
                            "margin-bottom",
                            "margin-xsmall",
                            "location-margin",
                            "dropdown-tab",
                            "landscape",
                            "mob",
                            "land"
                          )}
                          tag="div"
                        >
                          <_Builtin.Block
                            className={_utils.cx(_styles, "div-block-32")}
                            tag="div"
                          >
                            <_Builtin.Heading
                              className={_utils.cx(
                                _styles,
                                "heading-style-h5",
                                "mob"
                              )}
                              tag="h3"
                            >
                              {"‍"}
                              <_Builtin.Strong>
                                <_Builtin.Emphasized
                                  className={_utils.cx(
                                    _styles,
                                    "tabsize",
                                    "mob"
                                  )}
                                >
                                  {"SANTA MONICA, LA"}
                                </_Builtin.Emphasized>
                              </_Builtin.Strong>
                              {""}
                            </_Builtin.Heading>
                          </_Builtin.Block>
                          <_Builtin.Paragraph
                            className={_utils.cx(
                              _styles,
                              "paragraph-5",
                              "tab",
                              "mob"
                            )}
                          >
                            {
                              "Suspendisse facilisis mattis tellus augue risus nunc viverra eget sit ipsum nisl est sagittis adipiscing ornare at."
                            }
                          </_Builtin.Paragraph>
                          <_Builtin.Block
                            className={_utils.cx(_styles, "div-block-8", "mob")}
                            tag="div"
                          >
                            <_Builtin.Block
                              className={_utils.cx(
                                _styles,
                                "div-block-6",
                                "tab",
                                "mob"
                              )}
                              tag="div"
                            >
                              <_Builtin.Image
                                className={_utils.cx(_styles, "image")}
                                loading="lazy"
                                height="auto"
                                width="10"
                                alt=""
                                src="https://uploads-ssl.webflow.com/6547e1150d1404495b9400cd/654f17eecebe3e29b3a4fc9b_Vector.svg"
                              />
                              <_Builtin.Heading
                                className={_utils.cx(
                                  _styles,
                                  "heading-10",
                                  "tab",
                                  "mob"
                                )}
                                tag="h1"
                              >
                                {
                                  "987 L Woodland Hills St,Los Angeles, CA, 90012"
                                }
                              </_Builtin.Heading>
                            </_Builtin.Block>
                            <_Builtin.Block
                              className={_utils.cx(
                                _styles,
                                "div-block-7",
                                "tabview"
                              )}
                              tag="div"
                            >
                              <_Builtin.Image
                                className={_utils.cx(_styles, "image-2")}
                                loading="lazy"
                                height="auto"
                                width="10"
                                alt=""
                                src="https://uploads-ssl.webflow.com/6547e1150d1404495b9400cd/654f1a99d33458e14a2e1c81_Vector2.svg"
                              />
                              <_Builtin.Heading
                                className={_utils.cx(
                                  _styles,
                                  "heading-12",
                                  "tab",
                                  "mob"
                                )}
                                tag="h1"
                              >
                                {"(213) 427-0570"}
                              </_Builtin.Heading>
                            </_Builtin.Block>
                          </_Builtin.Block>
                        </_Builtin.Block>
                      </_Builtin.Block>
                    </_Builtin.Block>
                  </_Builtin.Block>
                  <_Builtin.Block
                    className={_utils.cx(
                      _styles,
                      "home_how-it-works_item",
                      "landscape"
                    )}
                    id={_utils.cx(
                      _styles,
                      "w-node-_08271253-e666-3828-5306-700e78623ef8-78623ec6"
                    )}
                    tag="div"
                  >
                    <_Builtin.Block
                      className={_utils.cx(
                        _styles,
                        "margin-bottom",
                        "margin-medium"
                      )}
                      tag="div"
                    >
                      <_Builtin.Block
                        className={_utils.cx(
                          _styles,
                          "home4-features_image-wrapper"
                        )}
                        tag="div"
                      >
                        <_Builtin.Image
                          className={_utils.cx(
                            _styles,
                            "home_how-it-works_image"
                          )}
                          loading="lazy"
                          width="400"
                          height="auto"
                          alt=""
                          src="https://uploads-ssl.webflow.com/6547e1150d1404495b9400cd/654c75ea26a9d252dad1aac3_Group%2027.png"
                        />
                      </_Builtin.Block>
                    </_Builtin.Block>
                    <_Builtin.Block
                      className={_utils.cx(
                        _styles,
                        "margin-bottom",
                        "margin-xsmall",
                        "location-margin",
                        "landscape",
                        "mob",
                        "land"
                      )}
                      tag="div"
                    >
                      <_Builtin.Heading
                        className={_utils.cx(_styles, "heading-style-h5")}
                        tag="h3"
                      >
                        <_Builtin.Emphasized
                          className={_utils.cx(_styles, "tabsize", "mob")}
                        >
                          {"WOODLAND HILLS, LA"}
                        </_Builtin.Emphasized>
                        {""}
                      </_Builtin.Heading>
                      <_Builtin.Paragraph
                        className={_utils.cx(
                          _styles,
                          "paragraph-6",
                          "tab",
                          "mob"
                        )}
                      >
                        {
                          "Suspendisse facilisis mattis tellus augue risus nunc viverra eget sit ipsum nisl est sagittis adipiscing ornare at."
                        }
                      </_Builtin.Paragraph>
                      <_Builtin.Block
                        className={_utils.cx(_styles, "div-block-8", "mob")}
                        tag="div"
                      >
                        <_Builtin.Block
                          className={_utils.cx(_styles, "div-block-6", "mob")}
                          tag="div"
                        >
                          <_Builtin.Image
                            className={_utils.cx(_styles, "image")}
                            loading="lazy"
                            height="auto"
                            width="10"
                            alt=""
                            src="https://uploads-ssl.webflow.com/6547e1150d1404495b9400cd/654f17eecebe3e29b3a4fc9b_Vector.svg"
                          />
                          <_Builtin.Heading
                            className={_utils.cx(
                              _styles,
                              "heading-10",
                              "tab",
                              "mob"
                            )}
                            tag="h1"
                          >
                            {"987 L Woodland Hills St,Los Angeles, CA, 90012"}
                          </_Builtin.Heading>
                        </_Builtin.Block>
                        <_Builtin.Block
                          className={_utils.cx(_styles, "div-block-7")}
                          tag="div"
                        >
                          <_Builtin.Image
                            className={_utils.cx(_styles, "image-2")}
                            loading="lazy"
                            height="auto"
                            width="10"
                            alt=""
                            src="https://uploads-ssl.webflow.com/6547e1150d1404495b9400cd/654f1a99d33458e14a2e1c81_Vector2.svg"
                          />
                          <_Builtin.Heading
                            className={_utils.cx(
                              _styles,
                              "heading-12",
                              "tab",
                              "mob"
                            )}
                            tag="h1"
                          >
                            {"(213) 427-0570"}
                          </_Builtin.Heading>
                        </_Builtin.Block>
                      </_Builtin.Block>
                    </_Builtin.Block>
                  </_Builtin.Block>
                </_Builtin.Grid>
              </_Builtin.Block>
            </_Builtin.Block>
          </_Builtin.Block>
        </_Builtin.Block>
      </_Builtin.Block>
    </_Component>
  );
}
