import "@/devlink/global.css";
import { DevLinkProvider } from "@/devlink/DevLinkProvider";
import { CartProvider } from "./pages/CartContext";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <DevLinkProvider>
          <CartProvider>
            {children}
          </CartProvider>
        </DevLinkProvider>
      </body>
    </html>
  );
}
